# -*- coding: utf-8 -*-
"""linearRegSingle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eZ5H6vup_aHNqTBTe7BJXrXh3TQg-ITS
"""

import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

housePrice = pd.read_csv("/resources/housePrice.csv")
housePrice

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel("Area")
plt.ylabel("Price")
plt.scatter(housePrice.area, housePrice.price, color="red", marker="+")

new_housePrice = housePrice.drop("price", axis="columns")
new_housePrice

model = linear_model.LinearRegression()
model.fit(new_housePrice, housePrice.price)

model.predict([[5000]])

model.coef_

model.intercept_

# y = m*x +b
135.78767123 * 5000 + 180616.43835616432

area_df = pd.read_csv("areaPredict.csv")
area_df

predictedPrice = model.predict(area_df)

area_df["prices"] = predictedPrice
area_df

area_df.to_csv("predictionCSV.csv")

df_canadaIncome = pd.read_csv("/resources/canadaIncome.csv")
# df_canadaIncome

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel("Year")
plt.ylabel("Income")
plt.scatter(df_canadaIncome.year, df_canadaIncome.income, marker = "+")

model_canadaIncome = linear_model.LinearRegression()
model_canadaIncome.fit(df_canadaIncome[["year"]], df_canadaIncome.income)

model_canadaIncome.predict([[2020]])

